export const PAGE_ROUTES = {
  ROOT_PATH: "/",
  HOME_PATH: "/home",
  HOME_GREY_PATH: "/home-grey",
  HOME_1_PATH: "/home1",
  HOME_1_GREY_PATH: "/home1-grey",
  HOME_2_PATH: "/home2",
  HOME_2_GREY_PATH: "/home2-grey",
  HOME_3_PATH: "/home3",
  EXPLORE_PATH: "/explore",
  EXPLORE_GREY_PATH: "/explore-grey",
  EXPLORE_2_PATH: "/explore2",
  EXPLORE_2_GREY_PATH: "/explore2Grey",
  RANKING_PATH: "/rangking",
  RANKING_GREY_PATH: "/rangking-grey",
  AUCTION_PATH: "/auction",
  AUCTION_GREY_PATH: "/auction-grey",
  HELPCENTER_PATH: "/help-center",
  HELPCENTER_GREY_PATH: "/help-center-grey",
  COLLECTION_PATH: "/collection/:collectionId",
  GET_COLLECTION_PATH: (id) => `/collection/${id}`,

  COLLECTION_GREY_PATH: "/collection-grey/:collectionId",
  GET_COLLECTION_GREY_PATH: (id) => `/collection-grey/${id}`,

  ITEM_DETAIL_PATH: "/item-detail/:nftId/:tokenId",
  GET_ITEM_DETAIL_PATH: (id) => `/item-detail/${id}`,

  ITEM_DETAIL_GREY_PATH: "/item-detail-grey/:nftId",
  GET_ITEM_DETAIL_GREY_PATH: (id) => `/item-detail-grey/${id}`,

  AUTHOR_PATH: "/author/:authorId",
  GET_AUTHOR_PATH: (id) => `/author/${id}`,

  AUTHOR_GREY_PATH: "/author-grey/:authorId",
  GET_AUTHOR_GREY_PATH: (id) => `/author-grey/${id}`,

  WALLET_PATH: "/wallet",
  LOGIN_PATH: "/login",
  LOGIN_GREY_PATH: "/login-grey",
  LOGIN_2_PATH: "/login-two",
  GALLERY_PATH: "/gallery",
  LOGIN_2_GREY_PATH: "/login-two-grey",
  REGISTER_PATH: "/register",
  REGISTER_GREY_PATH: "/register-grey",
  PRICE_PATH: "/price",
  WORKS_PATH: "/works",
  NEWS_PATH: "/news",

  NEWS_SINGLE_PATH: "/news/:postId",
  GET_NEWS_SINGLE_PATH: (id) => `/news/${id}`,

  CREATE_PATH: "/create",
  CREATE_COLLECTION_PATH: "/create-collection",
  CREATE_GREY_PATH: "/create-grey",
  CREATE_LISTING_PATH: "/create-listing",
  CREATE_AUCTION_PATH: "/create-auction",
  CREATE_3_PATH: "/create3",
  CREATE_OPTIONS_PATH: "/create-options",
  ACTIVITY_PATH: "/activity",
  ACTIVITY_GREY_PATH: "/activity-grey",
  CONTACT_PATH: "/contact",
  CONTACT_GREY_PATH: "/contact-grey",
  ELEGANT_ICONS_PATH: "/elegant-icons",
  ETLINE_ICONS_PATH: "/etline-icons",
  FONTAWESOME_ICONS_PATH: "/font-awesome-icons",
  ACCORDION_PATH: "/accordion",
  ALERTS_PATH: "/alerts",
  PROGRESSBAR_PATH: "/progress-bar",
  TABS_PATH: "/tabs",
  MINTER_PATH: "/mint",
  MINTER_GREY_PATH: "/minter",
};
